export const SCORING_CONFIG = Object.freeze({
  VERSION: "METRON 1.0.1",
  EFFECTIVE_DATE: "2026-09-08",
  RATING_MIN: 1,
  RATING_MAX: 99,
  RATING_MEDIAN: 50,
  CURRENT_CONFIDENCE_MATCHES: 15,
  MIN_OVERALL_MATCHES: 10,
  CURRENT_MIN_OVERALL_MATCHES: 1,
  FORMER_MIN_CAREER_MATCHES: 10,
  MIN_BLOCK_WEIGHT_COVERAGE: 0.6,
  MIN_OVERALL_WEIGHT_COVERAGE: 0.85,
  OVERALL_MATCH_GRADE_WEIGHT: 0.15,
  MAN_OF_MATCH_BONUS_MAX: 3,
  MAN_OF_MATCH_COMPONENTS: Object.freeze({
    total: 0.35,
    perMatch: 0.65,
  }),
  TENURE_BONUS_PER_ADDITIONAL_SEASON: 0.5,
  TENURE_BONUS_MAX: 3,
  AWARD_BONUSES: Object.freeze({
    top_scorer: 2,
    top_assist_provider: 2,
    player_of_year: 4,
  }),
  MATCH_WEIGHTS: Object.freeze({
    TEST_MATCH: 1,
    COMPETITION: 1.25,
    PROTOUR: 1.5,
  }),
  BLOCKS: Object.freeze({
    creation: Object.freeze({
      assists: Object.freeze({ weight: 0.15, direction: "higher" }),
      assistsPerMatch: Object.freeze({ weight: 0.3, direction: "higher" }),
      assistFrequency: Object.freeze({ weight: 0.25, direction: "higher" }),
      teamAssistShare: Object.freeze({ weight: 0.1, direction: "higher" }),
      recentAssists: Object.freeze({ weight: 0.1, direction: "higher" }),
      maxAssists: Object.freeze({ weight: 0.05, direction: "higher" }),
      assistStreak: Object.freeze({ weight: 0.05, direction: "higher" }),
    }),
    finishing: Object.freeze({
      goals: Object.freeze({ weight: 0.15, direction: "higher" }),
      goalsPerMatch: Object.freeze({ weight: 0.3, direction: "higher" }),
      scoringFrequency: Object.freeze({ weight: 0.25, direction: "higher" }),
      teamGoalShare: Object.freeze({ weight: 0.1, direction: "higher" }),
      recentGoals: Object.freeze({ weight: 0.1, direction: "higher" }),
      maxGoals: Object.freeze({ weight: 0.05, direction: "higher" }),
      scoringStreak: Object.freeze({ weight: 0.05, direction: "higher" }),
    }),
    offensive: Object.freeze({
      contributions: Object.freeze({ weight: 0.15, direction: "higher" }),
      contributionsPerMatch: Object.freeze({ weight: 0.3, direction: "higher" }),
      decisiveFrequency: Object.freeze({ weight: 0.25, direction: "higher" }),
      teamContributionShare: Object.freeze({ weight: 0.1, direction: "higher" }),
      recentContributions: Object.freeze({ weight: 0.1, direction: "higher" }),
      maxContributions: Object.freeze({ weight: 0.05, direction: "higher" }),
      decisiveStreak: Object.freeze({ weight: 0.05, direction: "higher" }),
    }),
    defensive: Object.freeze({
      goalsAgainstPerMatch: Object.freeze({ weight: 0.3, direction: "lower" }),
      defensiveDifference: Object.freeze({ weight: 0.3, direction: "higher" }),
      betterDefendedFrequency: Object.freeze({ weight: 0.2, direction: "higher" }),
      betterDefendedMatches: Object.freeze({ weight: 0.05, direction: "higher" }),
      bestDefensiveGame: Object.freeze({ weight: 0.05, direction: "lower" }),
      worstDefensiveGame: Object.freeze({ weight: 0.1, direction: "lower" }),
    }),
  }),
  OVERALL_BY_POSITION: Object.freeze({
    G: Object.freeze({ creation: 0.1, finishing: 0, defensive: 0.75 }),
    D: Object.freeze({ creation: 0.3, finishing: 0.15, defensive: 0.4 }),
    M: Object.freeze({ creation: 0.4, finishing: 0.225, defensive: 0.225 }),
    A: Object.freeze({ creation: 0.25, finishing: 0.4, defensive: 0.2 }),
    DEFAULT: Object.freeze({ creation: 0.4, finishing: 0.225, defensive: 0.225 }),
  }),
});
